[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[BASE]
source = "container"
container = "library/debian"
include_regex = "trixie-\\d*-slim"

[GLIBC]
source = "github"
github = "sgerrand/alpine-pkg-glibc"
use_max_tag = true

[AWS_CLI]
source = "github"
github = "aws/aws-cli"
use_max_tag = true
